from __future__ import annotations

import re
from pathlib import Path
from typing import List

from jinja2 import Template

from waterplan.models.schemas import LocationReport
from waterplan.output.markdown import format_report

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  :root {
    --blue: #1a56a0;
    --teal: #0e9b8a;
    --light: #f4f9ff;
    --dark: #1a1a2e;
  }
  body { font-family: Arial, sans-serif; color: var(--dark); margin: 0; padding: 0; }
  .cover {
    background: linear-gradient(135deg, var(--blue), var(--teal));
    color: white; padding: 60px 40px; min-height: 120px;
  }
  .cover h1 { font-size: 2em; margin: 0 0 8px; }
  .cover .meta { font-size: 0.9em; opacity: 0.85; }
  .content { padding: 30px 40px; }
  h2 { color: var(--blue); border-bottom: 2px solid var(--teal); padding-bottom: 4px; }
  h3 { color: var(--teal); }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.9em; }
  th { background: var(--blue); color: white; padding: 8px 12px; text-align: left; }
  td { padding: 7px 12px; border-bottom: 1px solid #ddd; }
  tr:nth-child(even) td { background: var(--light); }
  .match { color: #0b7b3e; font-weight: bold; }
  .failed { color: #c0392b; font-weight: bold; }
  .source-box {
    background: var(--light); border-left: 4px solid var(--teal);
    padding: 10px 14px; margin: 8px 0; border-radius: 0 4px 4px 0;
    font-size: 0.88em;
  }
  blockquote { font-style: italic; color: #555; border-left: 3px solid #ccc; margin: 6px 0; padding-left: 12px; }
  .page-break { page-break-after: always; }
  .footer { text-align: center; color: #888; font-size: 0.8em; margin-top: 40px; }
</style>
</head>
<body>
{% for report in reports %}
<div class="cover">
  <h1>📍 {{ report.location }}</h1>
  <div class="meta">
    Model: {{ report.model_used }} &nbsp;|&nbsp;
    Generated: {{ report.timestamp.strftime('%Y-%m-%d %H:%M UTC') }} &nbsp;|&nbsp;
    Pass rate: {{ "%.0f%%" | format(report.overall_pass_rate() * 100) }} &nbsp;|&nbsp;
    Sources: {{ report.total_sources() }}
  </div>
</div>
<div class="content">
{% for dim_name, emoji, label in [
    ('water_stress', '💧', 'Water Stress'),
    ('incidents', '⚠️', 'Incidents & Conflicts'),
    ('regulations', '📋', 'Regulations')
] %}
{% set dim = report[dim_name] %}
<h2>{{ emoji }} {{ label }}</h2>
<p>{{ dim.summary }}</p>
{% if dim.risk_score is not none %}<p><strong>Risk Score:</strong> {{ dim.risk_score }}/10</p>{% endif %}
{% if dim.confidence %}<p><strong>Confidence:</strong> {{ "%.0f%%" | format(dim.confidence * 100) }}</p>{% endif %}
<h3>Sources</h3>
{% for src in dim.sources %}
<div class="source-box">
  <strong>{% if src.validation_status.value == 'MATCH_FOUND' %}<span class="match">✅ MATCH FOUND</span>{% else %}<span class="failed">❌ FAILED VALIDATION</span>{% endif %}</strong><br>
  <strong>Title:</strong> {{ src.title }}<br>
  <strong>URL:</strong> <a href="{{ src.url }}">{{ src.url[:80] }}{% if src.url|length > 80 %}...{% endif %}</a><br>
  <blockquote>{{ src.excerpt[:300] }}{% if src.excerpt|length > 300 %}...{% endif %}</blockquote>
  <small>{{ src.validation_detail }}</small>
</div>
{% endfor %}
{% if dim.self_critique %}
<p><em>🔍 Self-critique: {{ dim.self_critique }}</em></p>
{% endif %}
{% endfor %}
</div>
{% if not loop.last %}<div class="page-break"></div>{% endif %}
{% endfor %}
<div class="footer">Generated by Waterplan Research Tool · waterplan.com</div>
</body>
</html>"""


def write_pdf(reports: List[LocationReport], path: Path) -> None:
    try:
        from weasyprint import HTML
    except ImportError:
        raise RuntimeError(
            "WeasyPrint is required for PDF output. Install it with: pip install weasyprint"
        )

    # Make reports accessible as dicts for Jinja2
    report_proxies = []
    for r in reports:
        proxy = r.model_dump()
        # Re-attach dim objects for template access
        proxy["water_stress"] = r.water_stress
        proxy["incidents"] = r.incidents
        proxy["regulations"] = r.regulations
        proxy["timestamp"] = r.timestamp
        proxy["overall_pass_rate"] = r.overall_pass_rate
        proxy["total_sources"] = r.total_sources
        report_proxies.append(proxy)

    template = Template(_HTML_TEMPLATE)
    html_content = template.render(reports=reports)
    HTML(string=html_content).write_pdf(str(path))
